### ISSUE TITLE
add translation into english

### ISSUE THREAD

**Issue by developeregrem** [developeregrem/fewohbee#18]
At the moment the tool is available only in german language. 
In this ticket english translations of all messages.de.xlf under translations/ shall be added.
New files must be named as messages.en.xlf
Afterwards the language can be changed to 'en' in the file env file see 
https://github.com/developeregrem/pve/blob/51685a00bf5cd5ae86bd195dc71abdb57f824510/.env.dist#L5

**Comment by cheeyingng** [comment]
Hi @developeregrem , I would like to help on this issue

**Comment by developeregrem** [comment]
Hi @cheeyingng great to hear from you and thanks for your support.
I want to use a translation management tool to organize all of the translations. I think this will make our live much more easier.
If you want to help to translate the application please register an account on my own traduora installation here: https://traduora.elchlepp.info afterwards I can grant access to the translation projects!

**Comment by cheeyingng** [comment]
Hi,

I have register an account with my email p16007522@student.newinti.edu.my,
do invite me to your project so i can work on the translation. Thank you.

**Comment by developeregrem** [comment]
I gave you access. If you need support let me know. You can contact me via mail info at fewohbee.de at any time.
(I removed your mail address above for privacy reasons)
