### ISSUE TITLE
Verbesserungsvorschläge

### ISSUE THREAD

**Issue by tobelger** [developeregrem/fewohbee#50]
Hi, ich habe fewohbee auf einem Debian 11 mit Nginx webserver seit einer Woche am laufen. Ich bin kein Freund von Docker und habe mich deshalb für die direkte Installation entschieden, was auf der VM jetzt auch eigentlich nicht so aufwendig ist.

Vorschlag 1: Erweiterung der Dokumentation
Vielleicht könntet ihr für den Konfiguration des Webservers eine Beispieldatei bereit stellen. Ich musste erst auf die Idee kommen Nginx zu sagen wie er mit Symfonie umgehen muss. Ich kann auch gerne meine Nginxconfig als Muster zur Verfügung stellen.

Vorschlag 2: Reserrvierungskalender variabler gestalten
Der Reservierungskalender ist bereits gut umgesetzt. Wir haben sehr wenige Wohnung und daher sieht er bei uns ein bisschen verloren aus. Außerrdem wünschen sich meine Anwender eine Jahresansicht. Könnte man hier nicht eine weitere Konfigurationsmöglichkeit einbauen die eine Jahresansicht ermöglicht, also z.b. jeden Monat als extra Kalenderzeile untereinander?

Aufjedenfall eine tolle einfache Software für eine kleine private Verwaltung,

Viele Grüße
Tobias

**Comment by developeregrem** [comment]
Hi Tobias,

danke für die Anregungen.
Bisher hatte ich mich bewusst dagegen entschieden auch eine Doku für ein "herkömmliches" Setup bereitzustellen, um so eben nur den von mir präferierten Weg pflegen zu müssen.
Als Referenz könnte man z.B. auch die nginx Konfig von fewohbee-dockerized nutzen. 
Siehe https://github.com/developeregrem/fewohbee-dockerized/blob/master/conf/nginx/site-enabled-https/01_fewohbee.snippet 
Falls deine Konfig davon abweicht, kannst du deine hier auch gerne mit einwerfen :)

Im docker-setup sind eben auch einige security best practices mit eingeflossen, um das Setup möglichst sicher zu gestalten.
Siehe z.B. [SSL/TLS Konfig](https://github.com/developeregrem/fewohbee-dockerized/blob/master/conf/nginx/snippets/sslconf.snippet) oder [Security Header](https://github.com/developeregrem/fewohbee-dockerized/blob/master/conf/nginx/snippets/header.snippet)
Ein Blick lohnt sich vielleicht auch in die [PHP Konfig](https://github.com/developeregrem/fewohbee-dockerized/blob/master/conf/php/conf.ini) zu werfen.

An deinem zweiten Vorschlag arbeite ich aktuell sogar schon! Ich hoffe in kürze die neue Version veröffentlichen zu können. Diese wird dann eine Jahresansicht beinhalten. Allerdings nur pro Zimmer, sonst wird das ganze schnell zu unübersichtlich mit mehreren Zimmern. Sobald dies fertig ist kannst du mir gerne Feedback geben, ob das für euch so passt.

viele Grüße
Alex

**Comment by developeregrem** [comment]
Hi @tobelger,

aktuell wurde eine neue Version von FewohBee veröffentlicht (3.2.0), wo es auch eine komplett neue Jahresansicht gibt (siehe auch https://github.com/developeregrem/fewohbee/releases/tag/3.2.0).
Ich hoffe, das ist für euch auch nutzbar :)
In der nächsten Version, werde ich die Einschränkung für den regulären Kalender auch noch etwas anpassen, sodass man hier einen variablen Anzeigezeitraum eintragen kann.
Gib mir gerne Feedback, falls es noch offene Punkte für euch gibt!

Außerdem habe ich mittlerweile auch einen kurzen Guide für eine herkömmliche Installation geschrieben:
https://github.com/developeregrem/fewohbee/wiki/LAMP-Stack:-Apache,-MySQL,-PHP-(Ubuntu-22)
(aktuell allerdings für Apache; nginx würde ich demnächst noch ergänzen)
Da ich das aber selbst nicht produktiv verwende, bin ich über Anregungen oder Verbesserungsvorschläge sehr dankbar.

**Comment by tobelger** [comment]
Hi, ich hatte ganz vergessen das letzte mal zu antworten. Die Mail von Github ist mir irgendwie untergegangen. 
Ich werde heute Abend mal auf meinem Server die neue Version installieren. 
Ich gebe sicher Rückmeldung :)

**Comment by tobelger** [comment]
Der Jahreskalender ist genau das, was wir gebraucht haben. 

Die Doku ist jedenfalls aus meiner Sicht jetzt vollständig. Habe mal testweise auf einem nackigen Ubuntu neu installiert. Die Schritte waren vollständig meiner Meinung nach. Anbei noch meine Nginx conf
[fewohbee.conf.txt](https://github.com/developeregrem/fewohbee/files/9004434/fewohbee.conf.txt)
.

**Comment by daking88** [comment]
@developeregrem I think we can close this.
