### ISSUE TITLE
Install Problem HTTP Error 500

### ISSUE THREAD

**Issue by dom-madrid** [developeregrem/fewohbee#53]
Hi,

Continuing with my install, after the bug fix provided, it went all the way to the end. Created a virtual host in Apache2 and got an error 500.

In the log, it shows as follows:

`[Fri May 13 22:48:33.967145 2022] [php:error] [pid 32344] [client 192.168.1.229:35050] PHP Fatal error:  Uncaught Error: Undefined constant Symfony\\Component\\HttpFoundation\\Request::HEADER_X_FORWARDED_ALL in /var/www/fewohbee/public/index.php:28\nStack trace:\n#0 {main}\n  thrown in /var/www/fewohbee/public/index.php on line 28`

What could I have missed in the install process ?

I am testing the install in Ubuntu 22.04 and Ubuntu 20.04 (with some packaegs adjustement to meet requirements). Same problem on both sides.

**Comment by developeregrem** [comment]
Hi, I haven't tried the setup you use so far but it seems that HEADER_X_FORWARDED_ALL is set somewhere which is not available in the application. Maybe you set it in apache?Have you followed the symfony guide here? https://symfony.com/doc/current/setup/web_server_configuration.htmlI really recommend to use the docker approach as this is maintained by me or at least try it with nginx maybe.-------- Ursprüngliche Nachricht --------Von: Dominique Couot ***@***.***>Datum: Fr., 13. Mai 2022, 22:56An: developeregrem/fewohbee ***@***.***>Cc: Subscribed ***@***.***>Betreff: [developeregrem/fewohbee] Install Problem HTTP Error 500 (Issue #53)
Hi,
Continuing with my install, after the bug fix provided, it went all the way to the end. Created a virtual host in Apache2 and got an error 500.
In the log, it shows as follows:
[Fri May 13 22:48:33.967145 2022] [php:error] [pid 32344] [client 192.168.1.229:35050] PHP Fatal error:  Uncaught Error: Undefined constant Symfony\\Component\\HttpFoundation\\Request::HEADER_X_FORWARDED_ALL in /var/www/fewohbee/public/index.php:28\nStack trace:\n#0 {main}\n  thrown in /var/www/fewohbee/public/index.php on line 28
What could I have missed in the install process ?
I am testing the install in Ubuntu 22.04 and Ubuntu 20.04 (with some packaegs adjustement to meet requirements). Same problem on both sides.

**Comment by developeregrem** [comment]
Have you solved your issue?
In the meantime I had some time to try the same LAMP stack as you did and wrote a short documentation where I was able to successfully launch the application at the end.
See here: [LAMP Stack](https://github.com/developeregrem/fewohbee/wiki/LAMP-Stack:-Apache,-MySQL,-PHP-(Ubuntu-22))

Feel free to make suggestions for improvements here :)
