### ISSUE TITLE
Default Login Values

### ISSUE THREAD

**Issue by deadrabbit87** [developeregrem/fewohbee#61]
Hi,

maybe a stupid question, where can i find the default login values of the docker installation?

Thanks!

BW

**Comment by developeregrem** [comment]
Hi @deadrabbit87,
no stupid question ;) If you were not prompted to enter your own credentials during setup, something went wrong.
Try to reset everything
```
cd /opt/fewohbee-dockerized
./cleanup.sh
rm .env
```
and run `./install.sh` again and watch the output for possible problems.
You can also take a look into the logfile and see whether something is in
```
docker-compose logs php
```

**Comment by deadrabbit87** [comment]
Hi, 

thanks a lot  for your answer. There was a problem with database setup, therefore i was not able to set a username and password. 

Now i've set fewoohbe on a LAMP-Stack and it worked.
