### ISSUE TITLE
2 Probleme in der UI

### ISSUE THREAD

**Issue by germanbeast** [developeregrem/fewohbee#68]
Hallo zusammen,

habe fewohbee auch seit ein paar Tagen am laufen und bin super zufrieden gerade auch für die Doku und Erstellung von Rechnungen
jedoch habe ich 2 Probleme in der UI die mit Server 500 Fehler angezeigt werden

Dies ist einmal beim löschen von einem Gast Sprich ich kann keinen angelegten Gast wieder löschen. Erhalte dort im Log folgenden Fehler 500:

`{"message":"Matched route \"customers.delete.customer\".","context":{"route":"customers.delete.customer","route_parameters":{"_route":"customers.delete.customer","_controller":"App\\Controller\\CustomerServiceController::deleteCustomerAction","id":"3"},"request_uri":"https://ferienwohnung/customers/3/delete","method":"POST"},"level":200,"level_name":"INFO","channel":"request","datetime":"2022-11-12T11:24:51.710099+01:00","extra":{}}
`

2tes Problem ist die Vorlagen Erstellung. Diese lädt ewig in der UI. Man kann nur die Vorlagen bearbeiten diese schon mit der Installation erstellt worden sind.

Eventuell könntest du mir vlt. weiterhelfen und Tipps geben.

Auf jeden fall auch nochmal ein dickes Lob an die Erstellung dieses OneManShow Projektes :-)

**Comment by developeregrem** [comment]
Hi und danke dir :)
da waren wirklich noch kleine Fehler drin, die ich eben behoben habe.
Bitte einfach `./update-docker.sh` im docker-compose Ordner ausführen, dann sollte auch die neue Version gezogen werden.

**Comment by germanbeast** [comment]
Super gerade geupdatet :-) nun funktioniert alles.

Besten dank für deine Hilfe und Behebung des Problems
