### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by RexNecross** [developeregrem/fewohbee#80]
Hi! I set up Apache, MySQL and PHP 8.2 and everything goes fine, login page loads fine, login works.

After Login i only get:

Warning: Undefined array key 0 in C:\xampp-3\htdocs\fewohbee\src\Controller\ReservationServiceController.php on line 71

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by developeregrem** [comment]
Hi,
is this a fresh installation without loading some initial test data?
If yes, I recommend to load test data:

`sudo -u www-data php bin/console doctrine:fixtures:load --append`
See: [Setup FewohBee](https://github.com/developeregrem/fewohbee/wiki/LAMP-Stack:-Apache,-MySQL,-PHP-(Ubuntu-22)#setup-fewohbee)

**Comment by developeregrem** [comment]
fixed the issue and added a hint when no initial test data was added
See: 22af58a83f5e30d3f25b38a434873dada5352d95
